#04_run_structural_models.R

#this script runs the correlated factor, hierarchical, and bifactor
#models with factors predicting differentiation and total problems,
#by sourcing the script: '04.1_specify_structural_models.R'.
#plots of the structural models based on these results 
#are generated by the script: '04.2_plot_structural_models.R'

#load necessary packages
library(GenomicSEM)
library(tidyverse)
library(flextable)
library(officer)

#load variance/covariance matrix of genomics associated with differentiation 
#and total scores, and liability to 11 psychiatric conditions
load(file="./data/cov_wpsych.RData")

#define common settings for all models
covstruc<-cov_wpsych
estimation<-"DWLS"
std.lv=FALSE

#specify structural models by sourcing:
source("./scripts/04.1_specify_structural_models.R")

#################################
### basic latent growth model ###
#################################

#run model with correlated factors predicting differentiation
Model_basic <- usermodel(covstruc=covstruc,
                         model=model_basic,
                         estimation=estimation,
                         std.lv=std.lv)
#model fit
Model_basic$modelfit #good fit

#results
Model_basic$results #little variation in the slope

################################
### correlated factor models ###
################################

#run model with correlated factors predicting differentiation
ModelD_4factors <- usermodel(covstruc=covstruc,
                             model=modelD_4factors,
                             estimation=estimation,
                             std.lv=std.lv)
#model fit
ModelD_4factors$modelfit #good fit

#filter results
tmpD4factors <- ModelD_4factors$results %>%
  filter(lhs%in%c("i","int","psy","neu","com"),
         op == "~"|op=="~~",
         (lhs=="i"&rhs%in%c("int","psy","neu","com"))|lhs==rhs,
         !rhs=="i") %>%
  mutate(model = "diff_4factors")

#print results
tmpD4factors

#save/load results
save(tmpD4factors, file="./output/tmpD4factors.RData")
load(file="./output/tmpD4factors.RData")

#run independent pathways model with specific effects on compulsive
#indicators, and effects on the other three factors
ModelD_4factors_com <- usermodel(covstruc=covstruc,
                                 model=modelD_4factors_com,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelD_4factors[[1]]$chisq-ModelD_4factors_com[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelD_4factors[[1]]$df[1]-ModelD_4factors_com[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_com_D<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelD_4factors_com[[1]],Q_chisq_pval_com_D)

#run independent pathways model with specific effects of psychotic
#indicators, and effects on the other three factors
ModelD_4factors_psy <- usermodel(covstruc=covstruc,
                                 model=modelD_4factors_psy,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelD_4factors[[1]]$chisq-ModelD_4factors_psy[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelD_4factors[[1]]$df[1]-ModelD_4factors_psy[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_psy_D<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelD_4factors_psy[[1]],Q_chisq_pval_psy_D)

#run independent pathways model with specific effects on neurodevelopmental
#indicators, and effects on the other three factors
ModelD_4factors_neu <- usermodel(covstruc=covstruc,
                                 model=modelD_4factors_neu,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelD_4factors[[1]]$chisq-ModelD_4factors_neu[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelD_4factors[[1]]$df[1]-ModelD_4factors_neu[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_neu_D<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelD_4factors_neu[[1]],Q_chisq_pval_neu_D)

#run independent pathways model with specific effects on internalising
#indicators, and effects on the other three factors
ModelD_4factors_int <- usermodel(covstruc=covstruc,
                                 model=modelD_4factors_int,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelD_4factors[[1]]$chisq-ModelD_4factors_int[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelD_4factors[[1]]$df[1]-ModelD_4factors_int[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_int_D<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelD_4factors_int[[1]],Q_chisq_pval_int_D)

#run model with correlated factors predicting total problems
ModelT_4factors <- usermodel(covstruc=covstruc,
                             model=modelT_4factors,
                             estimation=estimation,
                             std.lv=std.lv)
#print the model fit
ModelT_4factors$modelfit #good fit

#filter results
tmpT4factors <- ModelT_4factors$results %>%
  filter(lhs%in%c("i","int","psy","neu","com"),
         op == "~"|op=="~~",
         (lhs=="i"&rhs%in%c("int","psy","neu","com"))|lhs==rhs  ,
         !rhs=="i") %>%
  mutate(model = "tot_4factors")

#print results
tmpT4factors

#save/load results
save(tmpT4factors, file="./output/tmpT4factors.RData")
load(file="./output/tmpT4factors.RData")

#run independent pathways model with specific effects on compulsive
#indicators, and effects on the other three factors
ModelT_4factors_com <- usermodel(covstruc=covstruc,
                                 model=modelT_4factors_com,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelT_4factors[[1]]$chisq-ModelT_4factors_com[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelT_4factors[[1]]$df[1]-ModelT_4factors_com[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_com_T<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelT_4factors_com[[1]],Q_chisq_pval_com_T)

#run independent pathways model with specific effects on psychotic
#indicators, and effects on the other three factors
ModelT_4factors_psy <- usermodel(covstruc=covstruc,
                                 model=modelT_4factors_psy,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelT_4factors[[1]]$chisq-ModelT_4factors_psy[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelT_4factors[[1]]$df[1]-ModelT_4factors_psy[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_psy_T<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelT_4factors_psy[[1]],Q_chisq_pval_psy_T)

#run independent pathways model with specific effects on neurodevelopmental
#indicators, and effects on the other three factors
ModelT_4factors_neu <- usermodel(covstruc=covstruc,
                                 model=modelT_4factors_neu,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelT_4factors[[1]]$chisq-ModelT_4factors_neu[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelT_4factors[[1]]$df[1]-ModelT_4factors_neu[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_neu_T<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelT_4factors_neu[[1]],Q_chisq_pval_neu_T)

#run independent pathways model with specific effects on internalising
#indicators, and effects on the other three factors
ModelT_4factors_int <- usermodel(covstruc=covstruc,
                                 model=modelT_4factors_int,
                                 estimation=estimation,
                                 std.lv=std.lv)

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelT_4factors[[1]]$chisq-ModelT_4factors_int[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelT_4factors[[1]]$df[1]-ModelT_4factors_int[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_int_T<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelT_4factors_int[[1]],Q_chisq_pval_int_T)

## create table correlated factor model results

#load results
load(file="./output/tmpD4factors.RData")
load(file="./output/tmpT4factors.RData")

#differentiation ~ correlated factors
estsD_cor_all <- tmpD4factors %>% 
  mutate(Unstand_SE = as.numeric(Unstand_SE),
         STD_Genotype_SE = as.numeric(STD_Genotype_SE),
         across(where(is.numeric), ~ round(., 3))) %>%
  filter(op != "~~") %>%
  mutate(fdr_pval = p.adjust(p_value, method = "fdr")) %>%
  select(rhs,model,STD_All,fdr_pval) %>%
  `colnames<-`(c("predictor","model","STD_All","fdr_pval"))

# total problems ~ correlated factors
estsT_cor_all <- tmpT4factors %>% 
  mutate(Unstand_SE = as.numeric(Unstand_SE),
         STD_Genotype_SE = as.numeric(STD_Genotype_SE),
         across(where(is.numeric), ~ round(., 3))) %>%
  select(op,rhs,model,STD_All) %>%
  pivot_wider(names_from = op, values_from = STD_All) %>%
  `colnames<-`(c("predictor","model","STD_All","fdr_pval"))

# merge diff and tot
ests_cor_both <- estsD_cor_all %>%
  full_join(estsT_cor_all) %>%
  mutate(model=as.factor(model))

# rename factor levels
levels(ests_cor_both$model)[levels(ests_cor_both$model)=="diff_4factors"] <- "Differentiation"
levels(ests_cor_both$model)[levels(ests_cor_both$model)=="tot_4factors"] <- "Total problems"

df <- data.frame(
  model = rep(c("Total problems", "Differentiation"), each = 4),
  predictor = rep(c("int", "com", "neu", "psy"), times = 2),
  Q_pval = c(Q_chisq_pval_int_T, Q_chisq_pval_com_T, Q_chisq_pval_neu_T, Q_chisq_pval_psy_T,
             Q_chisq_pval_int_D, Q_chisq_pval_com_D, Q_chisq_pval_neu_D, Q_chisq_pval_psy_D))

# create table correlated factor model
tbl_cor_both <- ests_cor_both %>%
  left_join(df, by = c("model", "predictor")) %>%
  mutate(across(where(is.numeric), round, digits=2)) %>%
  select(model,predictor,STD_All,fdr_pval,Q_pval) %>%
  mutate(model = if_else(model == "Differentiation", "d", "t")) %>%
  pivot_wider(names_from = model, 
              values_from = c(STD_All,fdr_pval,Q_pval),
              names_sep = ".") %>%
  select(predictor, ends_with(".d"), ends_with(".t")) %>%
  mutate(predictor= as.factor(predictor))

levels(tbl_cor_both$predictor)[levels(tbl_cor_both$predictor)=="com"] <- "Compulsive"
levels(tbl_cor_both$predictor)[levels(tbl_cor_both$predictor)=="psy"] <- "Psychotic"
levels(tbl_cor_both$predictor)[levels(tbl_cor_both$predictor)=="neu"] <- "Neurodevelopmental"
levels(tbl_cor_both$predictor)[levels(tbl_cor_both$predictor)=="int"] <- "Internalising"

(ft_tbl_cor_both <- tbl_cor_both %>% 
    flextable() %>% 
    set_header_labels(values=list(predictor="Latent factor",
                                  STD_All.d="STD_EST",FDR_pval.d="",Q_pval_d="",
                                  STD_All.t="STD_EST",FDR_pval.t="",Q_pval_t="")) %>%
    add_header_row(values=list("","Differentiation","Total problems"), colwidths = c(1,3,3)) %>%
    compose(i = c(2,2), j = c(3,6), part = "header", value = as_paragraph("P",as_sub("FDR"))) %>%
    compose(i = c(2,2), j = c(4,7), part = "header", value = as_paragraph("Q",as_sub("pval"))) %>%
    flextable::font(fontname = "Arial", part= "all") %>% 
    theme_box() %>%
    border_outer(border=fp_border(color="gray80",width=2),part="all") %>%
    border_inner(border=fp_border(color='gray80',width=1),part="all") %>%
    hline(i=2,border=fp_border(color="gray50",width=3),part="header") %>%
    bg(bg="#F1F1F1",part="header") %>% 
    align(align = "center", part="all") %>% 
    set_table_properties(layout = "autofit"))

save_as_docx(ft_tbl_cor_both, path = "./tables/Table_S7_correlated_factor_output.docx")

##################################
### hierarchical factor models ###
##################################

#run hierarchical model with p-factor predicting differentiation
ModelD_hi_p <- usermodel(covstruc=covstruc,
                         model=modelD_hier_p,
                         estimation=estimation,
                         std.lv=std.lv)
#print the model fit
ModelD_hi_p$modelfit #acceptable fit

#filter results
diff_hier_p <- ModelD_hi_p$results %>%
  filter(lhs%in%c("i","p"),
         op == "~"|op=="~~",
         (lhs=="i"&rhs%in%c("p"))|lhs==rhs,
         !rhs=="i") %>%
  mutate(model = "diff_hier_p")

#print results
diff_hier_p

#save/load results
save(diff_hier_p, file="./output/diff_hier_p.RData")
load(file="./output/diff_hier_p.RData")

#run model with sub-factors from hierarchical model as predictors of differentiation
ModelD_hi_sub <- usermodel(covstruc=covstruc,
                           model=modelD_hi_sub,
                           estimation=estimation,
                           std.lv=std.lv)
#print the model fit
ModelD_hi_sub$modelfit #good fit

#filter results
diff_hier_sub <- ModelD_hi_sub$results %>%
  filter(lhs%in%c("i","int","psy","neu","com"),
         op == "~"|op=="~~",
         (lhs=="i"&rhs%in%c("int","psy","neu","com"))|lhs==rhs,
         !rhs=="i") %>%
  mutate(model = "diff_hier_sub")

#print results
diff_hier_sub

#save/load results
save(diff_hier_sub, file="./output/diff_hier_sub.RData")
load(file="./output/diff_hier_sub.RData")

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelD_hi_p[[1]]$chisq-ModelD_hi_sub[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelD_hi_p[[1]]$df[1]-ModelD_hi_sub[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_p_D<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelD_hi_p[[1]],Q_chisq_pval_p_D)

#run model of differentiation and total problems combined (as a sensitivity), 
#with p-factor from hierarchical model as predictor
ModelDT_hi_p <- usermodel(covstruc=covstruc,
                          model=modelDT_hi_p,
                          estimation=estimation,
                          std.lv=std.lv)
#print the model fit
ModelDT_hi_p$modelfit

#print results
ModelDT_hi_p$results

#run model of differentiation and total problems combined (as a sensitivity), 
#with sub-factors from hierarchical model as predictors
ModelDT_hi_sub <- usermodel(covstruc=covstruc,
                            model=modelDT_hi_sub,
                            estimation=estimation,
                            std.lv=std.lv)
#print the model fit
ModelDT_hi_sub$modelfit

#print results
ModelDT_hi_sub$results

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelDT_hi_p[[1]]$chisq-ModelDT_hi_sub[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelDT_hi_p[[1]]$df[1]-ModelDT_hi_sub[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelDT_hi_p[[1]],Q_chisq_pval)

#run model for total problems, with p-factor from hierarchical model as predictor
ModelT_hi_p <- usermodel(covstruc=covstruc,
                         model=modelT_hi_p,
                         estimation=estimation,
                         std.lv=std.lv)
#print the model fit
ModelT_hi_p$modelfit #acceptable fit

#filter results
tot_hier_p <- ModelT_hi_p$results %>%
  filter(lhs%in%c("i","p"),
         op == "~"|op=="~~",
         (lhs=="i"&rhs%in%c("p"))|lhs==rhs,
         !rhs=="i") %>%
  mutate(model = "tot_hier_p")

#print results
tot_hier_p

#save/load results
save(tot_hier_p, file="./output/tot_hier_p.RData")
load(file="./output/tot_hier_p.RData")

#run model for total problems with sub-factors from hierarchical model as predictors
ModelT_hi_sub <- usermodel(covstruc=covstruc,
                           model=modelT_hi_sub,
                           estimation=estimation,
                           std.lv=std.lv)
#print the model fit
ModelT_hi_sub$modelfit #acceptable fit

#filter results
tot_hier_sub <- ModelT_hi_sub$results %>%
  filter(lhs%in%c("i","com","psy","neu","int"),
         op == "~"|op=="~~",
         (lhs=="i"&rhs%in%c("com","psy","neu","int"))|lhs==rhs,
         !rhs=="i") %>%
  mutate(model = "tot_hier_sub")

#print results
tot_hier_sub

#save/load results
save(tot_hier_sub, file="./output/tot_hier_sub.RData")
load(file="./output/tot_hier_sub.RData")

#calculate the chi-square and save it in a vector called Q_chisq
Q_chisq<-ModelT_hi_p[[1]]$chisq-ModelT_hi_sub[[1]]$chisq

#calculate the df associated with this chi-square statistic and name it df
df<-ModelT_hi_p[[1]]$df[1]-ModelT_hi_sub[[1]]$df[1]

#calculate the p-value associated with the Q-statistic, using the relevant df. 
#This saves the p-values in a vector called Q_chisq_pval 
Q_chisq_pval_p_T<-pchisq(Q_chisq,df,lower.tail=FALSE)

cbind(ModelT_hi_p[[1]],Q_chisq_pval_p_T)

# create table hierarchical model

# load results
load(file="./output/diff_hier_p.RData")
load(file="./output/diff_hier_sub.RData")
load(file="./output/tot_hier_p.RData")
load(file="./output/tot_hier_sub.RData")

# merge hierarchical diff results
diff_hier_all <- diff_hier_p %>%
  full_join(diff_hier_sub)

# merge hierarchical tot results
tot_hier_all <- tot_hier_p %>%
  full_join(tot_hier_sub)

#differentiation ~ hierarchical
estsD_hi_all <- diff_hier_all %>% 
  mutate(Unstand_SE = as.numeric(Unstand_SE),
         STD_Genotype_SE = as.numeric(STD_Genotype_SE),
         across(where(is.numeric), ~ round(., 3))) %>%
  filter(op != "~~") %>%
  mutate(fdr_pval = p.adjust(p_value, method = "fdr")) %>%
  select(rhs,model,STD_All,fdr_pval) %>%
  `colnames<-`(c("predictor","model","STD_All","fdr_pval"))

# total problems ~ hierarchical
estsT_hi_all <- tot_hier_all %>% 
  mutate(Unstand_SE = as.numeric(Unstand_SE),
         STD_Genotype_SE = as.numeric(STD_Genotype_SE),
         across(where(is.numeric), ~ round(., 3))) %>%
  filter(op != "~~") %>%
  mutate(fdr_pval = p.adjust(p_value, method = "fdr")) %>%
  select(rhs,model,STD_All,fdr_pval) %>%
  `colnames<-`(c("predictor","model","STD_All","fdr_pval")) 

# merge diff and tot
ests_hi_both <- estsD_hi_all %>%
  full_join(estsT_hi_all) %>%
  mutate(model=as.factor(model))

# rename factor levels
levels(ests_hi_both$model)[levels(ests_hi_both$model)=="diff_hier_p"] <- "Differentiation"
levels(ests_hi_both$model)[levels(ests_hi_both$model)=="diff_hier_sub"] <- "Differentiation"
levels(ests_hi_both$model)[levels(ests_hi_both$model)=="tot_hier_p"] <- "Total problems"
levels(ests_hi_both$model)[levels(ests_hi_both$model)=="tot_hier_sub"] <- "Total problems"

# create dataframe to add Q_pval
df_hi <- data.frame(
  model = rep(c("Total problems", "Differentiation"), each = 1),
  predictor = rep(c("p"), times = 2),
  Q_pval = c(Q_chisq_pval_p_T,Q_chisq_pval_p_D))

# create table correlated factor model
tbl_hi_both <- ests_hi_both %>%
  left_join(df_hi, by = c("model", "predictor")) %>%
  mutate(across(where(is.numeric), round, digits=2)) %>%
  select(model,predictor,STD_All,fdr_pval,Q_pval) %>%
  mutate(model = if_else(model == "Differentiation", "d", "t")) %>%
  pivot_wider(names_from = model, 
              values_from = c(STD_All,fdr_pval,Q_pval),
              names_sep = ".") %>%
  select(predictor, ends_with(".d"), ends_with(".t")) %>%
  mutate(predictor=as.factor(predictor))

levels(tbl_hi_both$predictor)[levels(tbl_hi_both$predictor)=="p"] <- "P-factor"
levels(tbl_hi_both$predictor)[levels(tbl_hi_both$predictor)=="com"] <- "Compulsive"
levels(tbl_hi_both$predictor)[levels(tbl_hi_both$predictor)=="psy"] <- "Psychotic"
levels(tbl_hi_both$predictor)[levels(tbl_hi_both$predictor)=="neu"] <- "Neurodevelopmental"
levels(tbl_hi_both$predictor)[levels(tbl_hi_both$predictor)=="int"] <- "Internalising"

(ft_tbl_hi_both <- tbl_hi_both %>% 
    flextable() %>% 
    set_header_labels(values=list(rhs="Latent factor",
                                  STD_All.d="STD_EST",FDR_pval.d="",Q_pval.d="",
                                  STD_All.t="STD_EST",FDR_pval.t="",Q_pval.t="")) %>%
    add_header_row(values=list("","Differentiation","Total problems"), colwidths = c(1,3,3)) %>%
    compose(i = c(2,2), j = c(3,6), part = "header", value = as_paragraph("P",as_sub("FDR"))) %>%
    compose(i = c(2,2), j = c(4,7), part = "header", value = as_paragraph("Q",as_sub("pval"))) %>%
    flextable::font(fontname = "Arial", part= "all") %>% 
    theme_box() %>%
    border_outer(border=fp_border(color="gray80",width=2),part="all") %>%
    border_inner(border=fp_border(color='gray80',width=1),part="all") %>%
    hline(i=2,border=fp_border(color="gray50",width=3),part="header") %>%
    bg(bg="#F1F1F1",part="header") %>% 
    align(align = "center", part="all") %>% 
    set_table_properties(layout = "autofit"))

save_as_docx(ft_tbl_hi_both, path = "./tables/Table_S8_hierarchical_model_output.docx")

#######################
### bifactor models ###
#######################

#run model for diff with p from the bifactor model as predictor (not converging)
ModelD_bi_p <- usermodel(covstruc=covstruc,
                         model=modelD_bi_p,
                         estimation=estimation,
                         std.lv=std.lv)

#run model for diff with sub-factors from bifactor model as predictors
ModelD_bi_sub <- usermodel(covstruc=covstruc,
                           model=modelD_bi_sub,
                           estimation=estimation,
                           std.lv=std.lv)
#print the model fit
ModelD_bi_sub$modelfit #good fit

#print results
ModelD_bi_sub$results

#run model for tot with p from the bifactor model as predictor (not converging)
ModelT_bi_p <- usermodel(covstruc=covstruc,
                         model=modelT_bi_p,
                         estimation=estimation,
                         std.lv=std.lv)

#run model for tot w/sub-factors from bifactor as predictors (not converging)
ModelT_bi_sub<-usermodel(covstruc=covstruc,
                         model=modelT_bi_sub,
                         estimation=estimation,
                         std.lv=std.lv)

#plots and tables are generated in the script '04.2_plot_structural_models.R'

#Note abt standardised estimates: STD_All is fully standardised, STD_Genotype_SE 
#is only standardised with respect to the genetic variance in the phenotypes
#This is because, at present, the necessary components to obtain sandwich 
#corrected standard errors are not available for endogenous factors. Use STD_All
